monitor =,preferred,auto,auto

source = ~/.config/hypr/apps.conf
source = ~/.config/hypr/bind.conf
source = ~/.config/hypr/environment.conf
source = ~/.config/hypr/windowrule.conf
source = ~/.config/hypr/variables.conf
